### ISSUE TITLE
hydra.errors.MissingConfigException: In 'experiment/baseline': Could not find 'trainer/logger/WandbLogger'

### ISSUE THREAD

**Issue by yasamanparhizkar** [VectorInstitute/mmlearn#11]
### Describe the bug
Receiving a hydra error regarding a missing config `trainer/logger/WandbLogger`. I can see this config being named in `projects/med_benchmarking/configs/experiment/baseline.yaml` line 28:
```yaml
# @package _global_

defaults:
...
- /trainer/logger@trainer.logger.wandb: WandbLogger
...
```
However, I can't find a matching python script like `trainer/logger.py` or any other script where `WandbLogger` is defined.
How can I resolve this issue?

### To Reproduce
```bash
# clone mmlearn
git clone git@github.com:VectorInstitute/mmlearn.git

# create virtual env
python3 -m venv my_env
source my_env/bin/activate

# install mmlearn without any extra dependency
cd mmlearn
python3 -m pip install -e .

# install med_benchmarking dependencies
pip install -r projects/med_benchmarking/requirements.txt

# install some extra dependencies to resolve import issues
pip install pillow torchaudio opencv-python

# run baseline experiment
mmlearn_run 'hydra.searchpath=[pkg://projects.med_benchmarking.configs]' +experiment=baseline experiment_name=test
```

### Expected behavior
No output is printed before the Traceback. 
```bash
Traceback (most recent call last):
  File "path/to/venv/bin/mmlearn_run", line 8, in <module>
    sys.exit(main())
...
File "path/to/venv/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 488, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "path/to/venv/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'experiment/baseline': Could not find 'trainer/logger/WandbLogger'

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=pkg://mmlearn.conf
        provider=hydra.searchpath in command-line, path=pkg://projects.med_benchmarking.configs
        provider=schema, path=structured://
```

### Version
`mmlearn` version `0.1.0a0.dev2` installed from source.

**Comment by yasamanparhizkar** [comment]
**Solution:** `trainer/logger` is a hydra-zen config group, not a python script. It is defined in `mmlearn/conf/__init__.py` line 418 to 441:
```python
if _WANDB_AVAILABLE:
    register_external_modules(
        lightning_loggers,
        group="trainer/logger",
        provider="lightning",
        base_cls=lightning_loggers.Logger,
        ignore_cls=[lightning_loggers.WandbLogger],
    )
    external_store(
        builds(
            lightning_loggers.WandbLogger,
            populate_full_signature=True,
            name=II("experiment_name"),
            save_dir=SI("${hydra:runtime.output_dir}"),
            dir=SI("${hydra:runtime.output_dir}"),
            project=SI("${oc.env:WANDB_PROJECT}"),
            resume="allow",
            tags=II("tags"),
            job_type=II("job_type"),
        ),
        name="WandbLogger",
        group="trainer/logger",
        provider="lightning",
    )
```

If `wandb` isn't installed in your virtual env, `if _WANDB_AVAILABLE:` returns `False`; hence `trainer/logger` will not be defined.
To resolve the issue, install `wandb`:
```bash
pip install wandb
```

Then, run the experiment again:
```bash
mmlearn_run 'hydra.searchpath=[pkg://projects.med_benchmarking.configs]' +experiment=baseline experiment_name=test
```

**Comment by fcogidi** [comment]
How come `pip install -r projects/med_benchmarking/requirements.txt` didn't also install `wandb`? That seems like the appropriate place to add the dependency.

**Comment by yasamanparhizkar** [comment]
I don't know why. It does seem like it should have installed `wandb` ¯\_(ツ)_/¯
